title:              Croquette Blog
email:              dlsrks1218@daum.net
description:        Croquette's engineering blog!
author:             Croquette
baseurl:            ""
url:                "https://dlsrks1218.github.io"

# Social Profiles
twitter_username:   None
github_username:    dlsrks1218
facebook_username:  dlsrks1218
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough"]
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
