version: "3.3"

services:
    blog:
        image: jekyll/jekyll:latest
        command: bundle exec jekyll serve --force_polling --drafts --livereload --trace --host 0.0.0.0
        ports:
            - "4000:4000"   # jekyll 기본 포트
            - "80:4000" # nginx-proxy에게 포트를 알려주기위해
            - "35729:35729" # livereload를 위한 포트
        volumes:
            - ".:/srv/jekyll"