version: "3.3"

services:
    blog:
        image: jekyll/jekyll:latest
        command: bundle exec jekyll serve --force_polling --drafts --livereload --trace --host 0.0.0.0
        ports:
            - "4000:4000"   # jekyll 기본 포트
            - "35729:35729" # livereload를 위한 포트
        volumes:
            - ".:/srv/jekyll"
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - blog